export const UPDATE_INCOME = 'UPDATE_INCOME';
export const UPDATE_EXPENSES = 'UPDATE_EXPENSES';

export const ADD_EXPENSES = 'ADD_EXPENSES'
export const EDIT_EXPENSES = 'EDIT_EXPENSES'
export const DELETE_EXPENSES = 'DELETE_EXPENSES'